# Generated by Django 3.1.2 on 2020-10-29 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0001_initial'),
        ('brand', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('problem_image', models.ImageField(upload_to='', verbose_name='Problem Image')),
                ('solved', models.BooleanField(default=False)),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_service', to='brand.brand')),
                ('model_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_service', to='model.models')),
                ('servicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicer_service', to='account.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_service', to='account.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
