# Generated by Django 3.1.3 on 2020-11-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('service', '0005_service_vehicle_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vehicle_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_service', to='vehicles.vehicle'),
        ),
    ]
