# Generated by Django 3.1.3 on 2020-11-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20201105_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='vehicle_fk',
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
