# Generated by Django 3.1.3 on 2020-11-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_service_vehicle_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
