# Generated by Django 3.1.3 on 2020-11-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_service_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='mobile',
        ),
    ]
