# Generated by Django 3.1.3 on 2020-11-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_remove_service_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cancel_servicer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='cancel_user',
            field=models.BooleanField(default=False),
        ),
    ]
