# Generated by Django 3.1.3 on 2020-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20201106_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
    ]
