# Generated by Django 3.1.3 on 2020-11-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0003_auto_20201104_1926'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_vehicle', to='model.models')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_vehicle', to='account.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
